name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  stable-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    name: stable-x86_64-unknown-linux-gnu
    steps:
    - name: Repo checkout
      uses: actions/checkout@v2
    - name: Toolchain setup
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-unknown-linux-gnu
        toolchain: nightly
        override: true
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - name: Test release
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose

  stable-aarch64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    name: stable-aarch64-unknown-linux-gnu
    steps:
    - name: Repo checkout
      uses: actions/checkout@v2
    - name: Toolchain setup
      uses: actions-rs/toolchain@v1
      with:
        target: aarch64-unknown-linux-gnu
        toolchain: stable
        override: true
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - name: Test release
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose

  stable-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    name: stable-x86_64-pc-windows-msvc
    steps:
    - name: Repo checkout
      uses: actions/checkout@v2
    - name: Toolchain setup
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-pc-windows-msvc
        toolchain: nightly
        override: true
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - name: Test release
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose

  stable-x86_64-apple-darwin	:
      runs-on: macos-latest
      name: stable-x86_64-apple-darwin
      steps:
      - name: Repo checkout
        uses: actions/checkout@v2
      - name: Toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-apple-darwin
          toolchain: nightly
          override: true
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose
      - name: Test release
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --verbose

  nightly-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    name: nightly-x86_64-unknown-linux-gnu
    steps:
    - name: Repo checkout
      uses: actions/checkout@v2
    - name: Toolchain setup
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-unknown-linux-gnu
        toolchain: nightly
        override: true
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - name: Test release
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose

  nightly-aarch64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    name: nightly-aarch64-unknown-linux-gnu
    steps:
    - name: Repo checkout
      uses: actions/checkout@v2
    - name: Toolchain setup
      uses: actions-rs/toolchain@v1
      with:
        target: aarch64-unknown-linux-gnu
        toolchain: nightly
        override: true
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - name: Test release
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose

  nightly-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    name: nightly-x86_64-pc-windows-msvc
    steps:
    - name: Repo checkout
      uses: actions/checkout@v2
    - name: Toolchain setup
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-pc-windows-msvc
        toolchain: nightly
        override: true
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --verbose
    - name: Test release
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --verbose

  nightly-x86_64-apple-darwin	:
      runs-on: macos-latest
      name: nightly-x86_64-apple-darwin
      steps:
      - name: Repo checkout
        uses: actions/checkout@v2
      - name: Toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-apple-darwin
          toolchain: nightly
          override: true
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose
      - name: Test release
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --verbose

      
